import { bindActionCreators } from 'redux';
import { store } from '../store';

import { userLoginRequest,
  userSignupRequest,
  resetUserSignupData,
  fetchWareHouseRequest,
  fetchCategoryRequest,
  fetchProductRequest,
  orderPlaceRequest,
  fetchDriverWarehouseRequest,
  driverOrderListRequest,
  reserveOrderRequest,
  sendDriverLocationToserverRequest,
  addressListRequest,
  addAddressListRequest,
  deleteAddressListRequest,
  resetAddressData,
  orderPutBackRequest,
  cutomerPendingOrdersRequest,
  cutomerCompleteOrdersRequest,
  notificationListRequest,
  cancelOrderRequest,
  feedbackRequest,
  driverPendingOrdersRequest,
  pickedupOrderRequest,
  completedOrderRequest,
  driverCompleteOrdersListRequest,
  uploadDocumentRequest,
  uploadDeliveryDocumentRequest,
  fetchDriverDocRequest,
  uploadVehiclePhotoRequest,
  fetchProfileDataUrl,
  uploadPhotoRequest,
  fetchPhotoRequest,
  updateProfileRequest,
  fetchProfileRequest,
  earningDataRequest,
  updateDriverDocumentNumberRequest,
  onlineStatusRequest,
  driverReviewRequest }
  from './Authentication';

const actions = {
  userLoginRequest,
  userSignupRequest,
  resetUserSignupData,
  fetchWareHouseRequest,
  fetchCategoryRequest,
  fetchProductRequest,
  orderPlaceRequest,
  fetchDriverWarehouseRequest,
  driverOrderListRequest,
  reserveOrderRequest,
  sendDriverLocationToserverRequest,
  addressListRequest,
  addAddressListRequest,
  deleteAddressListRequest,
  resetAddressData,
  orderPutBackRequest,
  cutomerPendingOrdersRequest,
  cutomerCompleteOrdersRequest,
  notificationListRequest,
  cancelOrderRequest,
  feedbackRequest,
  driverPendingOrdersRequest,
  pickedupOrderRequest,
  completedOrderRequest,
  driverCompleteOrdersListRequest,
  uploadDocumentRequest,
  uploadDeliveryDocumentRequest,
  fetchDriverDocRequest,
  uploadVehiclePhotoRequest,
  fetchProfileDataUrl,
  uploadPhotoRequest,
  fetchPhotoRequest,
  updateProfileRequest,
  fetchProfileRequest,
  earningDataRequest,
  updateDriverDocumentNumberRequest,
  onlineStatusRequest,
  driverReviewRequest,
};

export default bindActionCreators(actions, store.dispatch);
